# Generated by Django 3.1 on 2020-08-16 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0007_auto_20200814_1802'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='done',
            field=models.BooleanField(default=False),
        ),
    ]
