# Generated by Django 3.1 on 2020-08-14 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_auto_20200814_2105'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyUser',
        ),
    ]
