# Generated by Django 3.1 on 2020-08-10 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_auto_20200809_1606'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quantity',
            name='user',
        ),
        migrations.RemoveField(
            model_name='product',
            name='quantity_user',
        ),
        migrations.AddField(
            model_name='product',
            name='quantity',
            field=models.IntegerField(default=1, null=True),
        ),
        migrations.DeleteModel(
            name='Item',
        ),
        migrations.DeleteModel(
            name='Quantity',
        ),
    ]
