# Generated by Django 3.1 on 2020-08-12 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_item'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Item',
        ),
    ]
