# Generated by Django 3.1 on 2020-08-16 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0022_auto_20200813_2127'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price_multiplier',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
