# Generated by Django 3.1 on 2020-08-18 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0023_product_price_multiplier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price_multiplier',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
    ]
